CREATE TABLE books (
    id INT IDENTITY(1,1) PRIMARY KEY,
    title NVARCHAR(255) NOT NULL,
    author NVARCHAR(255) NOT NULL,
    genre NVARCHAR(100) NOT NULL,
    year INT NOT NULL,
    country NVARCHAR(100) NOT NULL,
    period NVARCHAR(100) NOT NULL
);

-- Вставляємо всі книги
INSERT INTO books (title, author, genre, year, country, period) VALUES
(N'Голодні ігри', N'Сюзанна Коллінз', N'Dystopian', 2008, N'USA', N'Сучасна література'),
(N'Тінь і кістка', N'Лі Бардуго', N'Fantasy', 2012, N'USA', N'Сучасна література'),
(N'Двір шипів і троянд', N'Сара Дж. Маас', N'Romantic Fantasy', 2015, N'USA', N'Сучасна література'),
(N'1984', N'Джордж Орвелл', N'Dystopian', 1949, N'United Kingdom', N'Друга половина XX ст'),
(N'Хроніки Нарнії', N'К. С. Льюїс', N'Fantasy', 1950, N'United Kingdom', N'Друга половина XX ст'),
(N'Володар перснів', N'Дж. Р. Р. Толкін', N'Fantasy', 1955, N'United Kingdom', N'Друга половина XX ст'),
(N'Щоденник Анни Франк', N'Анна Франк', N'Biography', 1947, N'Netherlands', N'Друга половина XX ст'),
(N'Гордість і упередження', N'Джейн Остен', N'Romance', 1813, N'United Kingdom', N'Класична література XIX ст'),
(N'Джейн Ейр', N'Шарлотта Бронте', N'Romance', 1847, N'United Kingdom', N'Класична література XIX ст'),
(N'Іліада', N'Гомер', N'Classic', -800, N'Ancient Greece', N'Антична література'),
(N'Божественна комедія', N'Данте Аліг’єрі', N'Classic', 1320, N'Italy', N'Відродження XIV – XVI ст'),
(N'Гамлет', N'Вільям Шекспір', N'Classic', 1600, N'United Kingdom', N'Література Нового часу'),
(N'Темна матерія', N'Блейк Крауч', N'Science Fiction', 2016, N'USA', N'Сучасна література'),
(N'Дюна', N'Френк Герберт', N'Science Fiction', 1965, N'USA', N'Друга половина XX ст'),
(N'Таємничий острів', N'Жуль Верн', N'Adventure', 1875, N'France', N'Класична література XIX ст'),
(N'Одіссея', N'Гомер', N'Classic', -800, N'Ancient Greece', N'Антична література'),
(N'Біблія', N'Різні автори', N'Religious Literature', -750, N'Middle East', N'Антична література'),
(N'Прогрес пілігрима', N'Джон Баньян', N'Religious Literature', 1678, N'United Kingdom', N'Література Нового часу'),
(N'Просте християнство', N'К. С. Льюїс', N'Non-fiction', 1952, N'United Kingdom', N'Друга половина XX ст'),
(N'Трістан та Ізольда', N'Анонім', N'Romance', 1150, N'France', N'Середньовічна література'),
(N'Дон Кіхот', N'Мігель де Сервантес', N'Romance', 1605, N'Spain', N'Література Нового часу'),
(N'Мандри Гуллівера', N'Джонатан Свіфт', N'Adventure', 1726, N'United Kingdom', N'Література Нового часу'),
(N'Робінзон Крузо', N'Даніель Дефо', N'Adventure', 1719, N'United Kingdom', N'Література Нового часу'),
(N'Франкенштейн', N'Мері Шеллі', N'Speculative Fiction', 1818, N'United Kingdom', N'Класична література XIX ст'),
(N'Айвенго', N'Волтер Скотт', N'Historical Fiction', 1820, N'United Kingdom', N'Класична література XIX ст'),
(N'Повість временних літ', N'Нестор Літописець', N'Historical Fiction', 1113, N'Ukraine', N'Середньовічна література'),
(N'Слово о полку Ігоревім', N'Анонім', N'Classic', 1187, N'Ukraine', N'Середньовічна література'),
(N'Енеїда', N'Іван Котляревський', N'Classic', 1798, N'Ukraine', N'Класична література XIX ст'),
(N'Кавказ', N'Тарас Шевченко', N'Classic', 1845, N'Ukraine', N'Класична література XIX ст'),
(N'Кайдашева сім’я', N'Іван Нечуй-Левицький', N'Novella', 1878, N'Ukraine', N'Класична література XIX ст'),
(N'Лісова пісня', N'Леся Українка', N'Romance', 1911, N'Ukraine', N'Модернізм 1900-1945'),
(N'Кассандра', N'Леся Українка', N'Classic', 1907, N'Ukraine', N'Модернізм 1900-1945'),
(N'Тіні забутих предків', N'Михайло Коцюбинський', N'Novella', 1911, N'Ukraine', N'Модернізм 1900-1945'),
(N'Земля', N'Ольга Кобилянська', N'Novella', 1902, N'Ukraine', N'Модернізм 1900-1945'),
(N'Я (Романтика)', N'Микола Хвильовий', N'Classic', 1924, N'Ukraine', N'Модернізм 1900-1945'),
(N'Місто', N'Валер’ян Підмогильний', N'Romance', 1927, N'Ukraine', N'Модернізм 1900-1945'),
(N'Тигролови', N'Іван Багряний', N'Adventure', 1944, N'Ukraine', N'Модернізм 1900-1945'),
(N'Записки українського самашедшого', N'Ліна Костенко', N'Romance', 2010, N'Ukraine', N'Сучасна література'),
(N'Ворошиловград', N'Сергій Жадан', N'Classic', 2010, N'Ukraine', N'Сучасна література'),
(N'Колонія', N'Максим Кідрук', N'Science Fiction', 2022, N'Ukraine', N'Сучасна література'),
(N'Жорстокий принц', N'Голлі Блек', N'Romantic Fantasy', 2018, N'USA', N'Сучасна література');
GO